// src/components/home/NowSection.tsx
import { motion } from "framer-motion";
import SectionHeading from "@/components/shared/SectionHeading";
import { now } from "@/data";

interface Link {
    label: string;
    url: string;
}

interface Item {
    text: string;
    links?: Link[];
}

interface Section {
    title: string;
    items: Item[];
}

export default function NowSection() {
    return (
        <section id="now" className="mb-24 lg:mb-32">
            <SectionHeading className="mb-8">What I'm Doing Now</SectionHeading>

            <p className="text-neutral-500 mb-12 font-outfit">
                Last updated: {now.lastUpdated}
            </p>

            <div className="space-y-12">
                {now.sections.map((section: Section, index: number) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: index * 0.1 }}
                    >
                        <h3 className="text-2xl font-bold font-playfair mb-6 text-foreground/90">
                            {section.title}
                        </h3>
                        <ul className="space-y-4">
                            {section.items.map((item: Item, i: number) => (
                                <li key={i} className="text-lg text-neutral-400 font-outfit leading-relaxed whitespace-pre-line">
                                    <span className="block mb-1">{item.text}</span>
                                    {item.links && (
                                        <div className="flex flex-col gap-1 mt-1 ml-4">
                                            {item.links.map((link: Link, j: number) => (
                                                <a
                                                    key={j}
                                                    href={link.url}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="text-yellow-500/80 hover:text-yellow-500 transition-colors text-base"
                                                >
                                                    {link.label}
                                                </a>
                                            ))}
                                        </div>
                                    )}
                                </li>
                            ))}
                        </ul>
                    </motion.div>
                ))}
            </div>
        </section>
    );
}

// src/lib/components/home/NowSection.svelte
<script lang="ts">
	import { Motion } from 'svelte-motion';
	import SectionHeading from '$lib/components/shared/SectionHeading.svelte';
	import { now } from '$lib/data';
	import NowSectionItem from './NowSectionItem.svelte';
	import { inView } from '$lib/actions/inView';

	// Types
	interface Link {
		label: string;
		url: string;
	}

	interface Item {
		text: string;
		links?: Link[];
	}

	interface Section {
		title: string;
		items: Item[];
	}

	// State to track intersection for each item
	// We'll use a map or array. Since we iterate, we can just create a component for the item
	// or use an action that sets a local state variable in an each block?
	// Easier to extract the Item into a sub-component to handle its own state.
</script>

<section id="now" class="mb-24 lg:mb-32">
	<SectionHeading class="mb-8">{"What I'm Doing Now"}</SectionHeading>

	<p class="font-outfit mb-12 text-neutral-500">
		Last updated: {now.lastUpdated}
	</p>

	<div class="space-y-12">
		{#each now.sections as section, index}
			<NowSectionItem {section} {index} />
		{/each}
	</div>
</section>
