// src/lib/components/layout/VerticalEmail.svelte
<script lang="ts">
	import { email } from '$lib/data';

	let copied = $state(false);

	async function handleCopy() {
		try {
			await navigator.clipboard.writeText(email);
			copied = true;
			setTimeout(() => {
				copied = false;
			}, 2000);
		} catch (err) {
			console.error('Failed to copy: ', err);
		}
	}
</script>

<div
	class="fixed bottom-0 left-8 z-50 flex flex-col items-center gap-6 after:h-24 after:min-h-[100px] after:w-[1px] after:bg-neutral-500 after:content-[''] dark:after:bg-neutral-500"
>
	<button
		onclick={handleCopy}
		class="vertical-text relative font-mono text-sm tracking-widest transition-all duration-300 hover:-translate-y-1 hover:text-white"
		style="writing-mode: vertical-rl; color: var(--icon-color);"
	>
		{#if copied}
			<span class="font-bold text-green-400">Copied!!</span>
		{:else}
			{email}
		{/if}
	</button>
</div>

// src/components/layout/VerticalEmail.tsx

import { useState } from "react";

import { email } from "@/data";

export default function VerticalEmail() {
    const [copied, setCopied] = useState(false);


    const handleCopy = () => {
        navigator.clipboard.writeText(email);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="fixed left-8 bottom-0 z-50 flex flex-col items-center gap-6 after:h-24 after:min-h-[100px] after:w-[1px] after:bg-neutral-500 after:content-[''] dark:after:bg-neutral-500">
            <button
                onClick={handleCopy}
                className="vertical-text relative font-mono text-sm tracking-widest hover:text-white hover:-translate-y-1 transition-all duration-300"
                style={{ writingMode: "vertical-rl", color: 'var(--icon-color)' }}
            >
                {copied ? (
                    <span className="text-green-400 font-bold">Copied!!</span>
                ) : (
                    email
                )}
            </button>
        </div>
    );
}
