// src/components/shared/BlogItem.tsx

// Next imports removed

interface BlogItemProps {
    title: string;
    excerpt: string;
    date: string;
    slug: string;
    readTime: string;
    image?: string;
    showImage?: boolean;
}

export const BlogItem = ({ title, excerpt, date, slug, readTime, image, showImage = true }: BlogItemProps) => (
    <a
        href={slug}
        className="group flex flex-col md:flex-row-reverse gap-6 mb-12 items-center cursor-pointer p-4 rounded-xl transition-colors -mx-4"
        onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "color-mix(in oklab, var(--foreground) 5%, transparent)";
        }}
        onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
        }}
    >
        {/* Blog Image */}
        {showImage && image && (
            <div
                className="w-full md:w-48 h-32 relative flex-shrink-0 overflow-hidden rounded-lg"
                style={{
                    backgroundColor: "color-mix(in oklab, var(--foreground) 5%, transparent)",
                    border: "1px solid color-mix(in oklab, var(--foreground) 10%, transparent)",
                }}
            >
                <img
                    src={image}
                    alt={title}
                    className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
            </div>
        )}

        {/* Content */}
        <div className="flex-1 min-w-0">
            <div
                className="flex items-center gap-3 text-xs font-mono mb-2 uppercase tracking-wide"
                style={{ color: "color-mix(in oklab, var(--foreground) 50%, transparent)" }}
            >
                <span>{date}</span>
                <span>•</span>
                <span>{readTime}</span>
            </div>

            <h3
                className="text-xl font-bold transition-colors font-playfair mb-3 leading-tight"
                style={{ color: "var(--foreground)" }}
            >
                {title}
            </h3>

            <p
                className="text-sm leading-relaxed mb-4 line-clamp-3"
                style={{ color: "color-mix(in oklab, var(--foreground) 70%, transparent)" }}
            >
                {excerpt}
            </p>

            <div
                className="text-xs font-bold uppercase tracking-widest flex items-center gap-2 group-hover:gap-3 transition-all"
                style={{ color: "var(--foreground)" }}
            >
                Read Article <span className="text-yellow-600 dark:text-yellow-500">→</span>
            </div>
        </div>
    </a>
);

// src/lib/components/shared/BlogItem.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		title,
		excerpt,
		date,
		slug,
		readTime,
		image = undefined,
		showImage = true
	}: {
		title: string;
		excerpt: string;
		date: string;
		slug: string;
		readTime: string;
		image?: string;
		showImage?: boolean;
	} = $props();

	function handleMouseEnter(e: MouseEvent) {
		const target = e.currentTarget as HTMLElement;
		target.style.backgroundColor = 'color-mix(in oklab, var(--foreground) 5%, transparent)';
	}

	function handleMouseLeave(e: MouseEvent) {
		const target = e.currentTarget as HTMLElement;
		target.style.backgroundColor = 'transparent';
	}
</script>

<a
	href={`/blog/${slug}`}
	class="group -mx-4 mb-12 flex cursor-pointer flex-col items-center gap-6 rounded-xl p-4 transition-colors md:flex-row-reverse"
	onmouseenter={handleMouseEnter}
	onmouseleave={handleMouseLeave}
>
	<!-- Blog Image -->
	{#if showImage && image}
		<div
			class="relative h-32 w-full flex-shrink-0 overflow-hidden rounded-lg md:w-48"
			style="background-color: color-mix(in oklab, var(--foreground) 5%, transparent); border: 1px solid color-mix(in oklab, var(--foreground) 10%, transparent);"
		>
			<img
				src={image}
				alt={title}
				class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
			/>
		</div>
	{/if}

	<!-- Content -->
	<div class="min-w-0 flex-1">
		<div
			class="mb-2 flex items-center gap-3 font-mono text-xs tracking-wide uppercase"
			style="color: color-mix(in oklab, var(--foreground) 50%, transparent);"
		>
			<span>{date}</span>
			<span>•</span>
			<span>{readTime}</span>
		</div>

		<h3
			class="font-playfair mb-3 text-xl leading-tight font-bold transition-colors"
			style="color: var(--foreground);"
		>
			{title}
		</h3>

		<p
			class="mb-4 line-clamp-3 text-sm leading-relaxed"
			style="color: color-mix(in oklab, var(--foreground) 70%, transparent);"
		>
			{excerpt}
		</p>

		<div
			class="flex items-center gap-2 text-xs font-bold tracking-widest uppercase transition-all group-hover:gap-3"
			style="color: var(--foreground);"
		>
			Read Article <span class="text-yellow-600 dark:text-yellow-500">→</span>
		</div>
	</div>
</a>
