// src/lib/components/ui/AnimatedCounter.svelte
<script lang="ts">
	import { useMotionValue, useTransform, animate, Motion } from 'svelte-motion';
	import { onMount } from 'svelte';

	let { value } = $props();

	const count = useMotionValue(0);
	const rounded = useTransform(count, (latest) => Math.round(latest));

	$effect(() => {
		const controls = animate(count, value, { duration: 1, ease: 'easeOut' });
		return () => controls.stop();
	});
</script>

<Motion let:motion>
	<span use:motion>{$rounded}</span>
</Motion>

// src/components/ui/AnimatedCounter.tsx

import { useEffect } from "react";
import { useMotionValue, useTransform, animate, motion } from "framer-motion";

export default function AnimatedCounter({ value }: { value: number }) {
    const count = useMotionValue(0);
    const rounded = useTransform(count, (latest) => Math.round(latest));

    useEffect(() => {
        const controls = animate(count, value, { duration: 1, ease: "easeOut" });
        return () => controls.stop();
    }, [value, count]);

    return <motion.span>{rounded}</motion.span>;
}
